export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const ON_TIMER_DATA_LOAD = 'ON_TIMER_DATA_LOAD';
export const ON_SETTINGS_LOAD = 'ON_SETTINGS_LOAD';
export const ON_USER_ID_LOAD = 'ON_USER_ID_LOAD';
export const ON_NOTES_LOAD = 'ON_NOTES_LOAD';
export const ON_NOTES_PENDING = 'ON_NOTES_PENDING';

